on: push
jobs:
  check-environment:
    runs-on: ubuntu-latest
    steps:
      - name: check node version
        run: node -v
  build:
    name: 执行build打包命令
    permissions:
      contents: write
      pages: write      # 必须的权限，允许部署 Pages
      id-token: write   # 用于身份验证
    runs-on: ubuntu-latest
    steps: 
      - name: 克隆项目代码到运行环境
        uses: actions/checkout@v4

      - name: 安装依赖
        run: npm install

      - name: 构建打包
        run: npm run build

      - name: 部署Github Pages
        uses: JamesIves/github-pages-deploy-actions@v4
        with:
          branch: gh-pages
          folder: dist
