on: push

permissions:
  contents: write

jobs:
  check-environment:
    runs-on: ubuntu-latest
    steps:
      - name: check node version
        run: node -v
  build:
    name: 执行build打包命令
    
    runs-on: ubuntu-latest
    steps: 
      - name: 克隆项目代码到运行环境
        uses: actions/checkout@v4

      - name: 安装依赖
        run: npm install

      - name: 构建打包
        run: npm run build

      - name: 部署Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
